import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import BottomNav from "@/components/BottomNav";
import Navbar from "@/components/Navbar/Navbar";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Alamir Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <BottomNav />
        <Footer />
      </body>
    </html>
  );
}
